#ifndef _MAPS_H_
#define _MAPS_H_
#define MAP_a2
#define MAP_aerowalk
#define MAP_agenda
#define MAP_agent
#define MAP_aggressr
#define MAP_airar
#define MAP_alcyone
#define MAP_alk08dm
#define MAP_amphi
#define MAP_amphi2
#define MAP_androm9
#define MAP_argonaut
#define MAP_auhdm1
#define MAP_auhdm2
#define MAP_b256
#define MAP_b2s
#define MAP_badwalk
#define MAP_baldm2
#define MAP_baldm3
#define MAP_baldm4
#define MAP_baldm5
#define MAP_baldm6
#define MAP_baldm7
#define MAP_baldm8
#define MAP_battle
#define MAP_bless
#define MAP_blessed
#define MAP_blizz2
#define MAP_bovine
#define MAP_br11m
#define MAP_br13m
#define MAP_br18m
#define MAP_br20m
#define MAP_br21m
#define MAP_br21ma
#define MAP_bsdm6
#define MAP_bsdm7
#define MAP_bsdm8
#define MAP_bsp
#define MAP_carddm2
#define MAP_cathexis_vis
#define MAP_cbadm1
#define MAP_cbadm2
#define MAP_cbadm2v2
#define MAP_cbadm3
#define MAP_chesdm1
#define MAP_cleaver
#define MAP_cmt1b
#define MAP_cmt3
#define MAP_cmt4
#define MAP_cmt5b
#define MAP_condemn
#define MAP_cpm1qw
#define MAP_cpm3qw
#define MAP_crdm2
#define MAP_dakdm1
#define MAP_dakdm2
#define MAP_damaul7
#define MAP_dapak1
#define MAP_dapak10
#define MAP_dapak11
#define MAP_dapak12
#define MAP_dapak2
#define MAP_dapak3
#define MAP_dapak4
#define MAP_dapak5
#define MAP_dapak6
#define MAP_dapak7
#define MAP_dapak9
#define MAP_darkthree
#define MAP_dead
#define MAP_debello
#define MAP_del1
#define MAP_dm1
#define MAP_dm1a
#define MAP_dm2dmm4
#define MAP_dm3
#define MAP_dm3hill
#define MAP_dm3ish
#define MAP_dm4
#define MAP_dm4ish
#define MAP_dm5
#define MAP_dm5a
#define MAP_dm6
#define MAP_dm6dmm4
#define MAP_dm6quad
#define MAP_dm7
#define MAP_dm99a
#define MAP_dmfdm2
#define MAP_dmm4_1
#define MAP_dmm4_3
#define MAP_dp6
#define MAP_dranzdm6
#define MAP_dranzdm7
#define MAP_dranzdm8
#define MAP_dsn
#define MAP_duel1
#define MAP_e1m1
#define MAP_e1m2
#define MAP_e1m3
#define MAP_e1m5
#define MAP_e1m5duel
#define MAP_e1m6
#define MAP_e1m7
#define MAP_e2m1
#define MAP_e2m2
#define MAP_e2m2tdm
#define MAP_e2m5
#define MAP_e3m2
#define MAP_e3m7tdm
#define MAP_edc
#define MAP_efdm1
#define MAP_efdm10
#define MAP_efdm11
#define MAP_efdm12
#define MAP_efdm13
#define MAP_efdm2
#define MAP_efdm3
#define MAP_efdm4
#define MAP_efdm5
#define MAP_efdm6
#define MAP_efdm7
#define MAP_efdm8
#define MAP_efdm9
#define MAP_effigy
#define MAP_egyptele
#define MAP_elbow
#define MAP_end
#define MAP_enraged
#define MAP_eodm3
#define MAP_evdm1
#define MAP_exdm2
#define MAP_exdm3
#define MAP_exdm4
#define MAP_fbdm2
#define MAP_fbe3m7
#define MAP_ferrum
#define MAP_filthy
#define MAP_fmc
#define MAP_four
#define MAP_frag
#define MAP_fragtwn1
#define MAP_fribdev1
#define MAP_fribweb1
#define MAP_frobodm1
#define MAP_frobodm2
#define MAP_frobodm5
#define MAP_frontier
#define MAP_gencldm6
#define MAP_gendm2
#define MAP_genocide
#define MAP_geodm1
#define MAP_gomdm2
#define MAP_gomdm2v2
#define MAP_gomdm3
#define MAP_gomdm4
#define MAP_gomdm5
#define MAP_gomdm6
#define MAP_grim
#define MAP_hate
#define MAP_hill20
#define MAP_icearena
#define MAP_id3
#define MAP_ikdm9q1
#define MAP_imp1dm5
#define MAP_imp1dm6
#define MAP_impdm2
#define MAP_impdm3
#define MAP_inerb18b
#define MAP_infect
#define MAP_insomnia
#define MAP_jadm1
#define MAP_jndm6
#define MAP_jrdm1
#define MAP_jrdm2
#define MAP_jvoxdm2
#define MAP_jvx1
#define MAP_kdmw
#define MAP_kikdm3
#define MAP_kikdm6
#define MAP_kingdom
#define MAP_kjdm12
#define MAP_kjdm13
#define MAP_klzinsanity
#define MAP_klzvob
#define MAP_kz1on1a
#define MAP_lacrima
#define MAP_lady
#define MAP_leaks
#define MAP_lilith
#define MAP_lock
#define MAP_magus
#define MAP_maricsq1_1
#define MAP_maricsq1_2
#define MAP_matdm1
#define MAP_matdm2
#define MAP_mayhem
#define MAP_messy
#define MAP_midair3
#define MAP_mine
#define MAP_misdm10
#define MAP_misdm11a
#define MAP_misdm12
#define MAP_misdm13
#define MAP_misdm6
#define MAP_misdm8
#define MAP_misdm9
#define MAP_mjdm1pro
#define MAP_muny16
#define MAP_naked3
#define MAP_naked4
#define MAP_naked5
#define MAP_naked6
#define MAP_naked7b2
#define MAP_nduel
#define MAP_nindm2
#define MAP_nindm3
#define MAP_nindm3v2
#define MAP_njx9dm
#define MAP_noentry
#define MAP_odd1
#define MAP_odd2
#define MAP_oktest1
#define MAP_oldcrat
#define MAP_oldcrat2
#define MAP_oma
#define MAP_omf
#define MAP_opposit
#define MAP_outpost
#define MAP_p3a
#define MAP_pbrdm2
#define MAP_pen2
#define MAP_pidmm5
#define MAP_pinion1
#define MAP_pinion2
#define MAP_pinion3
#define MAP_pipeline
#define MAP_pkeg1
#define MAP_pkeg2
#define MAP_pldm1ex
#define MAP_pli
#define MAP_plpak1
#define MAP_plpak10
#define MAP_plpak11
#define MAP_plpak12
#define MAP_plpak2
#define MAP_plpak3
#define MAP_plpak4
#define MAP_plpak5
#define MAP_plpak6
#define MAP_plpak7
#define MAP_plpak8
#define MAP_plpak9
#define MAP_pope2
#define MAP_pope3
#define MAP_pope4
#define MAP_pope6
#define MAP_povdmm4
#define MAP_primedm
#define MAP_prodm4
#define MAP_pushdmm4
#define MAP_q1_q2dm1
#define MAP_q1arena
#define MAP_q1arenax
#define MAP_q1base1
#define MAP_q1edge
#define MAP_q1tm_speedy
#define MAP_q2dm7
#define MAP_q3dm6qw
#define MAP_qffldm5
#define MAP_qtdm1
#define MAP_qtourney2
#define MAP_quadrock
#define MAP_ranbase
#define MAP_rapture1
#define MAP_rapture2
#define MAP_rarena3
#define MAP_ravage
#define MAP_ravage2
#define MAP_razzi
#define MAP_rev68
#define MAP_rf2
#define MAP_rgarden
#define MAP_rip
#define MAP_ritual
#define MAP_rpdm10
#define MAP_rpgdm1
#define MAP_rtldm3
#define MAP_ruins
#define MAP_rwild
#define MAP_safe1
#define MAP_safe2
#define MAP_sanity
#define MAP_santzue
#define MAP_scampdm5
#define MAP_schloss
#define MAP_shadows
#define MAP_shadowsb7
#define MAP_shady
#define MAP_shake
#define MAP_shine
#define MAP_shroud
#define MAP_shroud2
#define MAP_silence
#define MAP_skull
#define MAP_skywalk
#define MAP_slip
#define MAP_sm
#define MAP_sm30_ray
#define MAP_spank1
#define MAP_spd
#define MAP_spear
#define MAP_spine
#define MAP_spinev2
#define MAP_start
#define MAP_strafin1
#define MAP_strafin2
#define MAP_strafin3
#define MAP_strafin4
#define MAP_strafin5
#define MAP_strafin6
#define MAP_strmland
#define MAP_sudden
#define MAP_summer
#define MAP_swtdie
#define MAP_tbase
#define MAP_tearena
#define MAP_teritory
#define MAP_theend
#define MAP_thf
#define MAP_timeless
#define MAP_titan2
#define MAP_trallefinal
#define MAP_trdmm4
#define MAP_trindm1
#define MAP_trindm2
#define MAP_trindm3
#define MAP_trondm1
#define MAP_trondm2
#define MAP_tsd
#define MAP_tumour2
#define MAP_uarena1
#define MAP_ukcldm2
#define MAP_ukcldm6
#define MAP_ukooldm2
#define MAP_ukooldm3
#define MAP_ukooldm4
#define MAP_ukooldm6
#define MAP_ukooldm8
#define MAP_ukpak1
#define MAP_ukpak2
#define MAP_ukpak5
#define MAP_ukpak6
#define MAP_ukpak8
#define MAP_ultrav
#define MAP_unddm1
#define MAP_unddm2
#define MAP_utressor
#define MAP_vdm2
#define MAP_vdm3
#define MAP_vendetta
#define MAP_vision1
#define MAP_warfare
#define MAP_warfare2
#define MAP_warfare3
#define MAP_wildtest
#define MAP_xl1dm1
#define MAP_xl1dm2
#define MAP_xl1dm3
#define MAP_xl1dm4
#define MAP_xl1dm5
#define MAP_xl1dm6
#define MAP_xl1dm7
#define MAP_ztndm1
#define MAP_ztndm2
#define MAP_ztndm3
#define MAP_ztndm4
#define MAP_ztndm5
#define MAP_ztndm6
#endif
